DASHBOARD_CARDS = {"System Information" = "system-information", "TrueNAS Help" = "help", "CPU" = "cpu", "Memory" = "memory", "Backup Tasks" = "backup", "Storage" = "storage", "Pool" = "pool-tank", "Network" = "network", "Interface" = "enp-1-s-0"}
DISK_LIST = ["sda", "sdb", "sdc", "sdd"]
# Execution delay will slow down WebUI.xpath by 10 misecond
EXECUTION_DELAY = 0.01
EXTRA_LONG_WAIT = 300
# IMPLICITLY_WAIT can not be higher than SHORT_WAIT
IMPLICITLY_WAIT = 1
KEYPATH = "~/.ssh/id_rsa_pytest"
LONG_WAIT = 60
MEDIUM_WAIT = 15
SHORT_WAIT = 5
WAIT = 30
SMB_ACL_ENTRY = [{"ae_who_sid" = "S-1-1-0", "ae_type" = "ALLOWED", "ae_perm" = "FULL"}]