import xpaths.apps
import xpaths.common_xpaths
import xpaths.dashboard
import xpaths.datasets
import xpaths.iscsi
import xpaths.local_users
import xpaths.services
import xpaths.sharing
import xpaths.smb
import xpaths.ssh
import xpaths.storage
