name: Comment on PR in Jira


on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  extract_issue_key:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Extract Jira issue key from PR title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_URL="${{ github.event.pull_request.html_url }}"

        # Debugging: Print the PR title and URL
        echo "PR_TITLE: $PR_TITLE"
        echo "PR_URL: $PR_URL"

        # Extract Jira issue key from the PR title or branch name
        ISSUE_KEY=$(echo "$PR_TITLE" | grep -oE 'TEN-[0-9]+')

        if [ -z "$ISSUE_KEY" ]; then
          echo "No Jira issue key found in the PR title"
          exit 1
        else
          echo "Jira issue key found: $ISSUE_KEY"
        fi

        COMMENT="Pull Request Created: [$PR_TITLE]($PR_URL)"
        
        # Create the JSON payload
        PAYLOAD=$(cat <<EOF
        {
          "body": "$COMMENT"
        }
        EOF
        )

        # Post comment to Jira
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -u $JIRA_USERNAME:$JIRA_API_TOKEN \
          --data "$PAYLOAD" \
          "$JIRA_URL/rest/api/2/issue/$ISSUE_KEY/comment")

        if [ "$RESPONSE" -eq 201 ]; then
          echo "Comment added successfully"
        else
          echo "Failed to add comment, response code: $RESPONSE"
          exit 1
        fi
